name: BanSystem
version: 1.4
main: me.pjsph.bansystem.Main
author: pjsph
commands:
  ban:
    description: Ban a player
  unban:
    description: Unban a player
  mute:
    description: Mute a player
  unmute:
    description: Unmute a player
  bansystem:
    description: Basic plugin commands