name: BanSystem
version: 1.3
main: me.pjsph.bansystem.Main
author: pjsph
commands:
  ban:
    description: Ban a player
  unban:
    description: Unban a player
  bansystem:
    description: Basic plugin commands